// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RequestChat } from '../chatbot/request-chat';


export enum Requests {
  NONE = 0,
  RequestChat = 1
}

export function unionToRequests(
  type: Requests,
  accessor: (obj:RequestChat) => RequestChat|null
): RequestChat|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestChat': return accessor(new RequestChat())! as RequestChat;
    default: return null;
  }
}

export function unionListToRequests(
  type: Requests, 
  accessor: (index: number, obj:RequestChat) => RequestChat|null, 
  index: number
): RequestChat|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestChat': return accessor(index, new RequestChat())! as RequestChat;
    default: return null;
  }
}
