// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RequestCommand } from '../sensact/request-command';
import { RequestStatus } from '../sensact/request-status';


export enum Requests {
  NONE = 0,
  RequestStatus = 1,
  RequestCommand = 2
}

export function unionToRequests(
  type: Requests,
  accessor: (obj:RequestCommand|RequestStatus) => RequestCommand|RequestStatus|null
): RequestCommand|RequestStatus|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestStatus': return accessor(new RequestStatus())! as RequestStatus;
    case 'RequestCommand': return accessor(new RequestCommand())! as RequestCommand;
    default: return null;
  }
}

export function unionListToRequests(
  type: Requests, 
  accessor: (index: number, obj:RequestCommand|RequestStatus) => RequestCommand|RequestStatus|null, 
  index: number
): RequestCommand|RequestStatus|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestStatus': return accessor(index, new RequestStatus())! as RequestStatus;
    case 'RequestCommand': return accessor(index, new RequestCommand())! as RequestCommand;
    default: return null;
  }
}
