// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ApplicationId } from '../application-id';


export class ResponseStatusItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseStatusItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():ApplicationId {
  return this.bb!.readUint16(this.bb_pos);
}

status():number {
  return this.bb!.readUint32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createResponseStatusItem(builder:flatbuffers.Builder, id: ApplicationId, status: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeInt32(status);
  builder.pad(2);
  builder.writeInt16(id);
  return builder.offset();
}

}
