// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponseStatusItem } from '../sensact/response-status-item';


export class ResponseStatus {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseStatus {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseStatus(bb:flatbuffers.ByteBuffer, obj?:ResponseStatus):ResponseStatus {
  return (obj || new ResponseStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseStatus(bb:flatbuffers.ByteBuffer, obj?:ResponseStatus):ResponseStatus {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseStatus()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

states(index: number, obj?:ResponseStatusItem):ResponseStatusItem|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ResponseStatusItem()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 8, this.bb!) : null;
}

statesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startResponseStatus(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStates(builder:flatbuffers.Builder, statesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, statesOffset, 0);
}

static startStatesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(8, numElems, 4);
}

static endResponseStatus(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponseStatus(builder:flatbuffers.Builder, statesOffset:flatbuffers.Offset):flatbuffers.Offset {
  ResponseStatus.startResponseStatus(builder);
  ResponseStatus.addStates(builder, statesOffset);
  return ResponseStatus.endResponseStatus(builder);
}
}
