// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RequestFbdRun {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestFbdRun {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestFbdRun(bb:flatbuffers.ByteBuffer, obj?:RequestFbdRun):RequestFbdRun {
  return (obj || new RequestFbdRun()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestFbdRun(bb:flatbuffers.ByteBuffer, obj?:RequestFbdRun):RequestFbdRun {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestFbdRun()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRequestFbdRun(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRequestFbdRun(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRequestFbdRun(builder:flatbuffers.Builder):flatbuffers.Offset {
  RequestFbdRun.startRequestFbdRun(builder);
  return RequestFbdRun.endRequestFbdRun(builder);
}
}
