// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RequestDebugData } from '../functionblock/request-debug-data';
import { RequestFbdRun } from '../functionblock/request-fbd-run';


export enum Requests {
  NONE = 0,
  RequestFbdRun = 1,
  RequestDebugData = 2
}

export function unionToRequests(
  type: Requests,
  accessor: (obj:RequestDebugData|RequestFbdRun) => RequestDebugData|RequestFbdRun|null
): RequestDebugData|RequestFbdRun|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestFbdRun': return accessor(new RequestFbdRun())! as RequestFbdRun;
    case 'RequestDebugData': return accessor(new RequestDebugData())! as RequestDebugData;
    default: return null;
  }
}

export function unionListToRequests(
  type: Requests, 
  accessor: (index: number, obj:RequestDebugData|RequestFbdRun) => RequestDebugData|RequestFbdRun|null, 
  index: number
): RequestDebugData|RequestFbdRun|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestFbdRun': return accessor(index, new RequestFbdRun())! as RequestFbdRun;
    case 'RequestDebugData': return accessor(index, new RequestDebugData())! as RequestDebugData;
    default: return null;
  }
}
