// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RequestDebugData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestDebugData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestDebugData(bb:flatbuffers.ByteBuffer, obj?:RequestDebugData):RequestDebugData {
  return (obj || new RequestDebugData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestDebugData(bb:flatbuffers.ByteBuffer, obj?:RequestDebugData):RequestDebugData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestDebugData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRequestDebugData(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRequestDebugData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRequestDebugData(builder:flatbuffers.Builder):flatbuffers.Offset {
  RequestDebugData.startRequestDebugData(builder);
  return RequestDebugData.endRequestDebugData(builder);
}
}
