// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ResponseFbdRun {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseFbdRun {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseFbdRun(bb:flatbuffers.ByteBuffer, obj?:ResponseFbdRun):ResponseFbdRun {
  return (obj || new ResponseFbdRun()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseFbdRun(bb:flatbuffers.ByteBuffer, obj?:ResponseFbdRun):ResponseFbdRun {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseFbdRun()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startResponseFbdRun(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endResponseFbdRun(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponseFbdRun(builder:flatbuffers.Builder):flatbuffers.Offset {
  ResponseFbdRun.startResponseFbdRun(builder);
  return ResponseFbdRun.endResponseFbdRun(builder);
}
}
