// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ResponseDebugData } from '../functionblock/response-debug-data';
import { ResponseFbdRun } from '../functionblock/response-fbd-run';


export enum Responses {
  NONE = 0,
  ResponseFbdRun = 1,
  ResponseDebugData = 2
}

export function unionToResponses(
  type: Responses,
  accessor: (obj:ResponseDebugData|ResponseFbdRun) => ResponseDebugData|ResponseFbdRun|null
): ResponseDebugData|ResponseFbdRun|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseFbdRun': return accessor(new ResponseFbdRun())! as ResponseFbdRun;
    case 'ResponseDebugData': return accessor(new ResponseDebugData())! as ResponseDebugData;
    default: return null;
  }
}

export function unionListToResponses(
  type: Responses, 
  accessor: (index: number, obj:ResponseDebugData|ResponseFbdRun) => ResponseDebugData|ResponseFbdRun|null, 
  index: number
): ResponseDebugData|ResponseFbdRun|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseFbdRun': return accessor(index, new ResponseFbdRun())! as ResponseFbdRun;
    case 'ResponseDebugData': return accessor(index, new ResponseDebugData())! as ResponseDebugData;
    default: return null;
  }
}
