// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ResponseStoreFingerSchedule {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseStoreFingerSchedule {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseStoreFingerSchedule(bb:flatbuffers.ByteBuffer, obj?:ResponseStoreFingerSchedule):ResponseStoreFingerSchedule {
  return (obj || new ResponseStoreFingerSchedule()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseStoreFingerSchedule(bb:flatbuffers.ByteBuffer, obj?:ResponseStoreFingerSchedule):ResponseStoreFingerSchedule {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseStoreFingerSchedule()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startResponseStoreFingerSchedule(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endResponseStoreFingerSchedule(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponseStoreFingerSchedule(builder:flatbuffers.Builder):flatbuffers.Offset {
  ResponseStoreFingerSchedule.startResponseStoreFingerSchedule(builder);
  return ResponseStoreFingerSchedule.endResponseStoreFingerSchedule(builder);
}
}
