// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ResponseFingerActionManually {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseFingerActionManually {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseFingerActionManually(bb:flatbuffers.ByteBuffer, obj?:ResponseFingerActionManually):ResponseFingerActionManually {
  return (obj || new ResponseFingerActionManually()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseFingerActionManually(bb:flatbuffers.ByteBuffer, obj?:ResponseFingerActionManually):ResponseFingerActionManually {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseFingerActionManually()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startResponseFingerActionManually(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endResponseFingerActionManually(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponseFingerActionManually(builder:flatbuffers.Builder):flatbuffers.Offset {
  ResponseFingerActionManually.startResponseFingerActionManually(builder);
  return ResponseFingerActionManually.endResponseFingerActionManually(builder);
}
}
