// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ResponseStoreFingerAction {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseStoreFingerAction {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseStoreFingerAction(bb:flatbuffers.ByteBuffer, obj?:ResponseStoreFingerAction):ResponseStoreFingerAction {
  return (obj || new ResponseStoreFingerAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseStoreFingerAction(bb:flatbuffers.ByteBuffer, obj?:ResponseStoreFingerAction):ResponseStoreFingerAction {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseStoreFingerAction()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startResponseStoreFingerAction(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endResponseStoreFingerAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponseStoreFingerAction(builder:flatbuffers.Builder):flatbuffers.Offset {
  ResponseStoreFingerAction.startResponseStoreFingerAction(builder);
  return ResponseStoreFingerAction.endResponseStoreFingerAction(builder);
}
}
