// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ResponseSystemData } from '../systeminfo/response-system-data';


export enum Responses {
  NONE = 0,
  ResponseSystemData = 1
}

export function unionToResponses(
  type: Responses,
  accessor: (obj:ResponseSystemData) => ResponseSystemData|null
): ResponseSystemData|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseSystemData': return accessor(new ResponseSystemData())! as ResponseSystemData;
    default: return null;
  }
}

export function unionListToResponses(
  type: Responses, 
  accessor: (index: number, obj:ResponseSystemData) => ResponseSystemData|null, 
  index: number
): ResponseSystemData|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseSystemData': return accessor(index, new ResponseSystemData())! as ResponseSystemData;
    default: return null;
  }
}
