// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ApplicationId {
  MASTER = 0,
  SNSCT_NODE_HS = 1,
  SNSCT_NODE_UP = 2,
  PUSHB_X1_XX1_3 = 3,
  PUSHB_X2_XX2_4 = 4,
  PUSHB_X3_XX3_5 = 5,
  PUSHB_X1_XX4__6 = 6,
  BLINDB_X2_XX1_7 = 7,
  DIM2B_X3_XX2_8 = 8,
  POWIT_X1_XX3_9 = 9,
  POWIT_X2_XX4_10 = 10,
  POWIT_X3_XX1_11 = 11,
  POWIT_X1_XX2_12 = 12,
  BLIND_X2_XX3_13 = 13,
  PWM___X3_XX4_14 = 14,
  STDBY_X1_XX1_15 = 15,
  SOUND_X2_XX2_0 = 16,
  ROTAR_X3_XX3_0 = 17,
  NO_APPLICATION = 65535
}
