// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { CanData } from './canmonitor/can-data';
export { Namespace } from './canmonitor/namespace';
export { NotifyCanMessage } from './canmonitor/notify-can-message';
