// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Namespace } from './chatbot/namespace';
export { RequestChat } from './chatbot/request-chat';
export { RequestWrapper } from './chatbot/request-wrapper';
export { Requests } from './chatbot/requests';
export { ResponseChat } from './chatbot/response-chat';
export { ResponseWrapper } from './chatbot/response-wrapper';
export { Responses } from './chatbot/responses';
