// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum eSchedule {
  Predefined = 0,
  OneWeekIn15Minutes = 1,
  SunRandom = 2
}
