// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { OneWeekIn15MinutesData } from '../scheduler/one-week-in15-minutes-data';


export class OneWeekIn15Minutes {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OneWeekIn15Minutes {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOneWeekIn15Minutes(bb:flatbuffers.ByteBuffer, obj?:OneWeekIn15Minutes):OneWeekIn15Minutes {
  return (obj || new OneWeekIn15Minutes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOneWeekIn15Minutes(bb:flatbuffers.ByteBuffer, obj?:OneWeekIn15Minutes):OneWeekIn15Minutes {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OneWeekIn15Minutes()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

data(obj?:OneWeekIn15MinutesData):OneWeekIn15MinutesData|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new OneWeekIn15MinutesData()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startOneWeekIn15Minutes(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, dataOffset, 0);
}

static endOneWeekIn15Minutes(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOneWeekIn15Minutes(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset):flatbuffers.Offset {
  OneWeekIn15Minutes.startOneWeekIn15Minutes(builder);
  OneWeekIn15Minutes.addData(builder, dataOffset);
  return OneWeekIn15Minutes.endOneWeekIn15Minutes(builder);
}
}
