// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Predefined {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Predefined {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPredefined(bb:flatbuffers.ByteBuffer, obj?:Predefined):Predefined {
  return (obj || new Predefined()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPredefined(bb:flatbuffers.ByteBuffer, obj?:Predefined):Predefined {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Predefined()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startPredefined(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endPredefined(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPredefined(builder:flatbuffers.Builder):flatbuffers.Offset {
  Predefined.startPredefined(builder);
  return Predefined.endPredefined(builder);
}
}
