// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RequestSchedulerList {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RequestSchedulerList {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRequestSchedulerList(bb:flatbuffers.ByteBuffer, obj?:RequestSchedulerList):RequestSchedulerList {
  return (obj || new RequestSchedulerList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRequestSchedulerList(bb:flatbuffers.ByteBuffer, obj?:RequestSchedulerList):RequestSchedulerList {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RequestSchedulerList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRequestSchedulerList(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRequestSchedulerList(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRequestSchedulerList(builder:flatbuffers.Builder):flatbuffers.Offset {
  RequestSchedulerList.startRequestSchedulerList(builder);
  return RequestSchedulerList.endRequestSchedulerList(builder);
}
}
