// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ResponseSchedulerSave {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResponseSchedulerSave {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResponseSchedulerSave(bb:flatbuffers.ByteBuffer, obj?:ResponseSchedulerSave):ResponseSchedulerSave {
  return (obj || new ResponseSchedulerSave()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResponseSchedulerSave(bb:flatbuffers.ByteBuffer, obj?:ResponseSchedulerSave):ResponseSchedulerSave {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResponseSchedulerSave()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startResponseSchedulerSave(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static endResponseSchedulerSave(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResponseSchedulerSave(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset):flatbuffers.Offset {
  ResponseSchedulerSave.startResponseSchedulerSave(builder);
  ResponseSchedulerSave.addName(builder, nameOffset);
  return ResponseSchedulerSave.endResponseSchedulerSave(builder);
}
}
