// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ResponseSchedulerList } from '../scheduler/response-scheduler-list';
import { ResponseSchedulerOpen } from '../scheduler/response-scheduler-open';
import { ResponseSchedulerSave } from '../scheduler/response-scheduler-save';


export enum Responses {
  NONE = 0,
  ResponseSchedulerList = 1,
  ResponseSchedulerOpen = 2,
  ResponseSchedulerSave = 3
}

export function unionToResponses(
  type: Responses,
  accessor: (obj:ResponseSchedulerList|ResponseSchedulerOpen|ResponseSchedulerSave) => ResponseSchedulerList|ResponseSchedulerOpen|ResponseSchedulerSave|null
): ResponseSchedulerList|ResponseSchedulerOpen|ResponseSchedulerSave|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseSchedulerList': return accessor(new ResponseSchedulerList())! as ResponseSchedulerList;
    case 'ResponseSchedulerOpen': return accessor(new ResponseSchedulerOpen())! as ResponseSchedulerOpen;
    case 'ResponseSchedulerSave': return accessor(new ResponseSchedulerSave())! as ResponseSchedulerSave;
    default: return null;
  }
}

export function unionListToResponses(
  type: Responses, 
  accessor: (index: number, obj:ResponseSchedulerList|ResponseSchedulerOpen|ResponseSchedulerSave) => ResponseSchedulerList|ResponseSchedulerOpen|ResponseSchedulerSave|null, 
  index: number
): ResponseSchedulerList|ResponseSchedulerOpen|ResponseSchedulerSave|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseSchedulerList': return accessor(index, new ResponseSchedulerList())! as ResponseSchedulerList;
    case 'ResponseSchedulerOpen': return accessor(index, new ResponseSchedulerOpen())! as ResponseSchedulerOpen;
    case 'ResponseSchedulerSave': return accessor(index, new ResponseSchedulerSave())! as ResponseSchedulerSave;
    default: return null;
  }
}
