// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { OneWeekIn15Minutes } from '../scheduler/one-week-in15-minutes';
import { Predefined } from '../scheduler/predefined';
import { SunRandom } from '../scheduler/sun-random';


export enum uSchedule {
  NONE = 0,
  Predefined = 1,
  OneWeekIn15Minutes = 2,
  SunRandom = 3
}

export function unionTouSchedule(
  type: uSchedule,
  accessor: (obj:OneWeekIn15Minutes|Predefined|SunRandom) => OneWeekIn15Minutes|Predefined|SunRandom|null
): OneWeekIn15Minutes|Predefined|SunRandom|null {
  switch(uSchedule[type]) {
    case 'NONE': return null; 
    case 'Predefined': return accessor(new Predefined())! as Predefined;
    case 'OneWeekIn15Minutes': return accessor(new OneWeekIn15Minutes())! as OneWeekIn15Minutes;
    case 'SunRandom': return accessor(new SunRandom())! as SunRandom;
    default: return null;
  }
}

export function unionListTouSchedule(
  type: uSchedule, 
  accessor: (index: number, obj:OneWeekIn15Minutes|Predefined|SunRandom) => OneWeekIn15Minutes|Predefined|SunRandom|null, 
  index: number
): OneWeekIn15Minutes|Predefined|SunRandom|null {
  switch(uSchedule[type]) {
    case 'NONE': return null; 
    case 'Predefined': return accessor(index, new Predefined())! as Predefined;
    case 'OneWeekIn15Minutes': return accessor(index, new OneWeekIn15Minutes())! as OneWeekIn15Minutes;
    case 'SunRandom': return accessor(index, new SunRandom())! as SunRandom;
    default: return null;
  }
}
