// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RequestGetUserSettings } from '../usersettings/request-get-user-settings';
import { RequestSetUserSettings } from '../usersettings/request-set-user-settings';


export enum Requests {
  NONE = 0,
  RequestGetUserSettings = 1,
  RequestSetUserSettings = 2
}

export function unionToRequests(
  type: Requests,
  accessor: (obj:RequestGetUserSettings|RequestSetUserSettings) => RequestGetUserSettings|RequestSetUserSettings|null
): RequestGetUserSettings|RequestSetUserSettings|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestGetUserSettings': return accessor(new RequestGetUserSettings())! as RequestGetUserSettings;
    case 'RequestSetUserSettings': return accessor(new RequestSetUserSettings())! as RequestSetUserSettings;
    default: return null;
  }
}

export function unionListToRequests(
  type: Requests, 
  accessor: (index: number, obj:RequestGetUserSettings|RequestSetUserSettings) => RequestGetUserSettings|RequestSetUserSettings|null, 
  index: number
): RequestGetUserSettings|RequestSetUserSettings|null {
  switch(Requests[type]) {
    case 'NONE': return null; 
    case 'RequestGetUserSettings': return accessor(index, new RequestGetUserSettings())! as RequestGetUserSettings;
    case 'RequestSetUserSettings': return accessor(index, new RequestSetUserSettings())! as RequestSetUserSettings;
    default: return null;
  }
}
