// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { ResponseGetUserSettings } from '../usersettings/response-get-user-settings';
import { ResponseSetUserSettings } from '../usersettings/response-set-user-settings';


export enum Responses {
  NONE = 0,
  ResponseGetUserSettings = 1,
  ResponseSetUserSettings = 2
}

export function unionToResponses(
  type: Responses,
  accessor: (obj:ResponseGetUserSettings|ResponseSetUserSettings) => ResponseGetUserSettings|ResponseSetUserSettings|null
): ResponseGetUserSettings|ResponseSetUserSettings|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseGetUserSettings': return accessor(new ResponseGetUserSettings())! as ResponseGetUserSettings;
    case 'ResponseSetUserSettings': return accessor(new ResponseSetUserSettings())! as ResponseSetUserSettings;
    default: return null;
  }
}

export function unionListToResponses(
  type: Responses, 
  accessor: (index: number, obj:ResponseGetUserSettings|ResponseSetUserSettings) => ResponseGetUserSettings|ResponseSetUserSettings|null, 
  index: number
): ResponseGetUserSettings|ResponseSetUserSettings|null {
  switch(Responses[type]) {
    case 'NONE': return null; 
    case 'ResponseGetUserSettings': return accessor(index, new ResponseGetUserSettings())! as ResponseGetUserSettings;
    case 'ResponseSetUserSettings': return accessor(index, new ResponseSetUserSettings())! as ResponseSetUserSettings;
    default: return null;
  }
}
