// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BooleanSetting } from '../usersettings/boolean-setting';
import { EnumSetting } from '../usersettings/enum-setting';
import { IntegerSetting } from '../usersettings/integer-setting';
import { StringSetting } from '../usersettings/string-setting';


export enum Setting {
  NONE = 0,
  StringSetting = 1,
  IntegerSetting = 2,
  BooleanSetting = 3,
  EnumSetting = 4
}

export function unionToSetting(
  type: Setting,
  accessor: (obj:BooleanSetting|EnumSetting|IntegerSetting|StringSetting) => BooleanSetting|EnumSetting|IntegerSetting|StringSetting|null
): BooleanSetting|EnumSetting|IntegerSetting|StringSetting|null {
  switch(Setting[type]) {
    case 'NONE': return null; 
    case 'StringSetting': return accessor(new StringSetting())! as StringSetting;
    case 'IntegerSetting': return accessor(new IntegerSetting())! as IntegerSetting;
    case 'BooleanSetting': return accessor(new BooleanSetting())! as BooleanSetting;
    case 'EnumSetting': return accessor(new EnumSetting())! as EnumSetting;
    default: return null;
  }
}

export function unionListToSetting(
  type: Setting, 
  accessor: (index: number, obj:BooleanSetting|EnumSetting|IntegerSetting|StringSetting) => BooleanSetting|EnumSetting|IntegerSetting|StringSetting|null, 
  index: number
): BooleanSetting|EnumSetting|IntegerSetting|StringSetting|null {
  switch(Setting[type]) {
    case 'NONE': return null; 
    case 'StringSetting': return accessor(index, new StringSetting())! as StringSetting;
    case 'IntegerSetting': return accessor(index, new IntegerSetting())! as IntegerSetting;
    case 'BooleanSetting': return accessor(index, new BooleanSetting())! as BooleanSetting;
    case 'EnumSetting': return accessor(index, new EnumSetting())! as EnumSetting;
    default: return null;
  }
}
